DROP TABLE IF EXISTS projects CASCADE;

CREATE TABLE "projects" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT, 
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);